### ISSUE TITLE
Question: should this 34 be 24?

### ISSUE THREAD

**Issue by ewhitley** [projecttacoma/cqm-reports#65]
I'm looking at the QRDA I section importer and saw this:

https://github.com/projecttacoma/cqm-reports/blob/3320297a08c7130ad077d076e4282214f2960bcc/lib/qrda-import/base-importers/section_importer.rb#L142

```
        # Expected units are H (hours) and D (days)
        if unit && unit.upcase == 'D'
          low = low * 24 if low
          high = high * 34 if high
        end
```

Assuming we're converting days to hours, should the 34 in the "high" calculation be 24?

Thank you,
Eric

**Comment by dczulada** [comment]
Yes, it should be.  I don't know how that slipped by. Thanks.

**Comment by ewhitley** [comment]
Sorry to ask another follow-up, but as I looked I thought of something. If we're converting the value from days to hours (n * 24), should we also convert the unit from "D" to "H"?

**Comment by dczulada** [comment]
This for pointing this out.  We have pulled these changes into master.

https://github.com/projecttacoma/cqm-reports/pull/66

**Comment by ewhitley** [comment]
Thank you. Amazing turn-around!
